"""Gate E / P0-1: freeze the NV experimental observable definitions.

This revision removes the previous observable mismatch: the ensemble input was
normalized contrast C, while the Monte-Carlo generator assumed the order of the
raw signed absorption difference Delta A. Both observables are now carried
explicitly and never share an order or a floor silently.

Definitions
-----------
  Delta A = A_cut - A_full
      numerator order 4, no normalization denominator -> nu = 4.
  C = Delta A / A_cut
      Delta A order 4 and A_cut order 1 -> nu = 3.

The order of C is therefore derived from the observable definition rather than
entered as an independent hard-coded "true order". The ensemble values are
read from Gate 5, whose CSV now carries C, A_cut at the C peak, and Delta A at
the same point. The 70 K contrast floor remains frozen from Gate D. The raw
Delta-A floor is the same detection chain expressed in raw-response units:
Delta A_min = C_min * A_cut.

This gate remains a power/identifiability audit, not an end-to-end full-model
pseudoexperiment. The first finite-Gamma correction is a frozen synthetic
stress parameter; P0-3 replaces it with a coefficient generated by the full NV
model.
"""
from __future__ import annotations

import csv
import json
import math
from dataclasses import asdict, dataclass
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
REPO_ROOT = HERE.parents[2]
TABLES = ROOT / "results" / "tables"
ENSEMBLE_CSV = (
    REPO_ROOT
    / "No-go theorem"
    / "results"
    / "tables"
    / "gate5_ensemble_contrast.csv"
)
TABLES.mkdir(parents=True, exist_ok=True)

SEED = 20260807
TARGET_SNR_AT_FLOOR = 5.0
REQUIRED_GAMMA_DECADES = 1.0
SIGNED_RESPONSE_ORDER = 4
CUT_ABSORPTION_ORDER = 1
FIRST_CORRECTION_COEFFICIENT = 0.30
MULTIPLICATIVE_DRIFT = 0.03
N_POINTS = 16
N_MONTE_CARLO = 5000
GATING_SCENARIO = "post_selected_shimmed"

# Frozen from Gate D at the same 70 K candidate point.
C_MIN_70K = 1.1599051535422284e-6


@dataclass(frozen=True)
class EnsemblePoint:
    scenario: str
    contrast: float
    cut_absorption: float
    signed_absorption_difference: float


@dataclass(frozen=True)
class ObservableDefinition:
    key: str
    label: str
    numerator_order: int
    denominator_order: int
    unit: str

    @property
    def order(self) -> int:
        return self.numerator_order - self.denominator_order


OBSERVABLES = {
    "signed_absorption_difference": ObservableDefinition(
        key="signed_absorption_difference",
        label="raw signed absorption difference Delta A = A_cut - A_full",
        numerator_order=SIGNED_RESPONSE_ORDER,
        denominator_order=0,
        unit="reduced absorption",
    ),
    "normalized_contrast": ObservableDefinition(
        key="normalized_contrast",
        label="normalized contrast C = Delta A / A_cut",
        numerator_order=SIGNED_RESPONSE_ORDER,
        denominator_order=CUT_ABSORPTION_ORDER,
        unit="dimensionless",
    ),
}


@dataclass(frozen=True)
class WindowResult:
    scenario: str
    observable: str
    observable_label: str
    order: int
    reference_value: float
    detection_floor: float
    margin_over_floor: float
    window_decades: float
    improvement_to_one_decade: float
    unit: str


def load_ensemble_points(path: Path = ENSEMBLE_CSV) -> dict[str, EnsemblePoint]:
    required = {"scenario", "Cmax", "Aoff_at_Cmax", "dA_at_Cmax"}
    with path.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        missing = required.difference(reader.fieldnames or ())
        if missing:
            raise ValueError(
                f"{path} lacks P0-1 observable columns: {sorted(missing)}; "
                "rerun No-go theorem/src/gate5_ensemble_average.py"
            )
        points = {
            row["scenario"]: EnsemblePoint(
                scenario=row["scenario"],
                contrast=float(row["Cmax"]),
                cut_absorption=float(row["Aoff_at_Cmax"]),
                signed_absorption_difference=float(row["dA_at_Cmax"]),
            )
            for row in reader
        }
    if GATING_SCENARIO not in points:
        raise ValueError(f"gating scenario {GATING_SCENARIO!r} missing from {path}")
    return points


def observable_reference(
    point: EnsemblePoint, observable: ObservableDefinition
) -> float:
    if observable.key == "normalized_contrast":
        return point.contrast
    if observable.key == "signed_absorption_difference":
        return point.signed_absorption_difference
    raise KeyError(observable.key)


def observable_floor(point: EnsemblePoint, observable: ObservableDefinition) -> float:
    if observable.key == "normalized_contrast":
        return C_MIN_70K
    if observable.key == "signed_absorption_difference":
        return C_MIN_70K * point.cut_absorption
    raise KeyError(observable.key)


def usable_window_decades(reference: float, floor: float, order: float) -> float:
    """Largest Gamma window before a Gamma^-order signal reaches its floor."""
    if reference <= floor or order <= 0:
        return 0.0
    return float(math.log10(abs(reference) / abs(floor)) / order)


def window_table(
    points: dict[str, EnsemblePoint] | None = None,
) -> list[WindowResult]:
    points = load_ensemble_points() if points is None else points
    rows: list[WindowResult] = []
    for scenario, point in points.items():
        for observable in OBSERVABLES.values():
            reference = observable_reference(point, observable)
            floor = observable_floor(point, observable)
            margin = abs(reference / floor)
            window = usable_window_decades(reference, floor, observable.order)
            required_margin = 10.0 ** (
                observable.order * REQUIRED_GAMMA_DECADES
            )
            rows.append(
                WindowResult(
                    scenario=scenario,
                    observable=observable.key,
                    observable_label=observable.label,
                    order=observable.order,
                    reference_value=float(reference),
                    detection_floor=float(floor),
                    margin_over_floor=float(margin),
                    window_decades=window,
                    improvement_to_one_decade=float(
                        max(1.0, required_margin / margin)
                    ),
                    unit=observable.unit,
                )
            )
    return rows


def _fit_candidate(
    x: np.ndarray, y: np.ndarray, order: int, correction: float | None
) -> float:
    """Return RSS for one candidate integer order."""
    if correction is None:
        design = np.column_stack(
            [np.ones_like(x), x ** (-order), x ** (-(order + 1))]
        )
    else:
        feature = x ** (-order) * (1.0 + correction / x)
        design = np.column_stack([np.ones_like(x), feature])
    beta, *_ = np.linalg.lstsq(design, y, rcond=None)
    residual = y - design @ beta
    return float(np.dot(residual, residual))


def monte_carlo_identifiability(
    reference: float,
    floor: float,
    true_order: int,
    window_decades: float,
    correction_constrained: bool,
    seed: int = SEED,
) -> dict:
    rng = np.random.default_rng(seed)
    x = np.logspace(0.0, window_decades, N_POINTS)
    correction_value = FIRST_CORRECTION_COEFFICIENT
    amplitude = reference / (1.0 + correction_value)
    truth = amplitude * x ** (-true_order) * (1.0 + correction_value / x)
    sigma_additive = floor / TARGET_SNR_AT_FLOOR

    candidates = (true_order - 1, true_order, true_order + 1)
    wins = {order: 0 for order in candidates}
    for _ in range(N_MONTE_CARLO):
        measured = truth * (
            1.0 + rng.normal(0.0, MULTIPLICATIVE_DRIFT, N_POINTS)
        )
        measured += rng.normal(0.0, sigma_additive, N_POINTS)
        correction = correction_value if correction_constrained else None
        rss = {
            order: _fit_candidate(x, measured, order, correction)
            for order in candidates
        }
        wins[min(rss, key=rss.get)] += 1

    probabilities = {
        str(order): wins[order] / N_MONTE_CARLO for order in candidates
    }
    return {
        "window_decades": float(window_decades),
        "n_points": N_POINTS,
        "n_monte_carlo": N_MONTE_CARLO,
        "true_order": true_order,
        "candidate_orders": list(candidates),
        "first_correction_coefficient": correction_value,
        "multiplicative_drift": MULTIPLICATIVE_DRIFT,
        "additive_sigma": float(sigma_additive),
        "high_end_snr": float(abs(truth[-1] / sigma_additive)),
        "correction_constrained": correction_constrained,
        "selection_probability": probabilities,
        "correct_class_probability": probabilities[str(true_order)],
    }


def main() -> None:
    points = load_ensemble_points()
    rows = window_table(points)
    gating_rows = {
        row.observable: row
        for row in rows
        if row.scenario == GATING_SCENARIO
    }

    identifiability: dict[str, dict[str, dict]] = {}
    for key, row in gating_rows.items():
        identifiability[key] = {
            "constrained": monte_carlo_identifiability(
                row.reference_value,
                row.detection_floor,
                row.order,
                row.window_decades,
                correction_constrained=True,
            ),
            "unconstrained": monte_carlo_identifiability(
                row.reference_value,
                row.detection_floor,
                row.order,
                row.window_decades,
                correction_constrained=False,
            ),
        }

    normalized = gating_rows["normalized_contrast"]
    raw = gating_rows["signed_absorption_difference"]
    gates = {
        "G_E1_both_observables_detectable": bool(
            normalized.margin_over_floor > 1.0
            and raw.margin_over_floor > 1.0
        ),
        "G_E2_normalized_contrast_one_decade_window": bool(
            normalized.window_decades >= REQUIRED_GAMMA_DECADES
        ),
        "G_E3_raw_signed_difference_one_decade_window": bool(
            raw.window_decades >= REQUIRED_GAMMA_DECADES
        ),
        "G_E4_model_constrained_identifiability_both": bool(
            all(
                result["constrained"]["correct_class_probability"] >= 0.95
                for result in identifiability.values()
            )
        ),
        "G_E5_unconstrained_identifiability_both": bool(
            all(
                result["unconstrained"]["correct_class_probability"] >= 0.95
                for result in identifiability.values()
            )
        ),
        "G_E6_observable_orders_derived_consistently": bool(
            OBSERVABLES["signed_absorption_difference"].order == 4
            and OBSERVABLES["normalized_contrast"].order == 3
        ),
    }

    verdict = "CONDITIONAL_PASS"
    temperature_ratio_for_one_gamma_decade = 10.0 ** (
        REQUIRED_GAMMA_DECADES / 5.0
    )
    summary = {
        "description": (
            "Gate E P0-1: observable-consistent NV "
            "exponent-identifiability audit"
        ),
        "provenance": {
            "contrast_floor": (
                "GateD_robustness_discriminability/results/tables/"
                "gates_summary_gateD.json"
            ),
            "ensemble_observables": str(ENSEMBLE_CSV.relative_to(REPO_ROOT)),
            "candidate_temperature_K": 70.0,
        },
        "observable_definitions": {
            key: {**asdict(observable), "derived_order": observable.order}
            for key, observable in OBSERVABLES.items()
        },
        "assumptions": {
            "Gamma_T_power": 5.0,
            "required_gamma_decades": REQUIRED_GAMMA_DECADES,
            "finite_Gamma_model": "O=A Gamma^-n (1+b/Gamma)+background",
            "finite_Gamma_coefficient_status": (
                "synthetic frozen stress parameter; replace in P0-3"
            ),
            "raw_floor_conversion": (
                "DeltaA_min = C_min * A_cut at the same ensemble feature"
            ),
        },
        "window_rows": [asdict(row) for row in rows],
        "gating_scenario": GATING_SCENARIO,
        "temperature_ratio_for_one_gamma_decade": (
            temperature_ratio_for_one_gamma_decade
        ),
        "identifiability": identifiability,
        "gates": gates,
        "verdict": verdict,
        "interpretation": {
            "primary_theory_observable": (
                "raw signed absorption difference Delta A, nu=4"
            ),
            "primary_direct_experimental_observable": (
                "normalized contrast C, nu=3"
            ),
            "normalized_contrast_window": (
                "GO for a one-decade signal window (1.119 decades)"
            ),
            "raw_signed_difference_window": (
                "NO-GO for a one-decade signal window (0.839 decades)"
            ),
            "free_exponent_fit": (
                "NO-GO for both observables with a freely refitted "
                "finite-Gamma correction/background"
            ),
            "model_constrained_fit": (
                "GO for both observables if the leading correction is fixed "
                "independently before fitting"
            ),
            "paper_role": (
                "Use Delta A for the theorem statement and C for direct NV "
                "data; connect them by the explicit A_cut normalization law. "
                "NV remains a model-constrained experimental anchor until "
                "P0-3 supplies the full-model finite-Gamma correction."
            ),
        },
    }

    with (TABLES / "gates_summary_gateE.json").open(
        "w", encoding="utf-8"
    ) as f:
        json.dump(summary, f, indent=2)

    with (TABLES / "gate_e_windows.csv").open(
        "w", newline="", encoding="utf-8"
    ) as f:
        fieldnames = list(asdict(rows[0]).keys())
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(asdict(row))

    with (TABLES / "gate_e_identifiability.csv").open(
        "w", newline="", encoding="utf-8"
    ) as f:
        fieldnames = [
            "observable",
            "fit",
            "true_order",
            "candidate_orders",
            "correct_class_probability",
            "p_lower",
            "p_true",
            "p_upper",
            "window_decades",
            "high_end_snr",
        ]
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for key, fit_results in identifiability.items():
            for label, result in fit_results.items():
                true_order = result["true_order"]
                probabilities = result["selection_probability"]
                writer.writerow(
                    {
                        "observable": key,
                        "fit": label,
                        "true_order": true_order,
                        "candidate_orders": ";".join(
                            str(order) for order in result["candidate_orders"]
                        ),
                        "correct_class_probability": result[
                            "correct_class_probability"
                        ],
                        "p_lower": probabilities[str(true_order - 1)],
                        "p_true": probabilities[str(true_order)],
                        "p_upper": probabilities[str(true_order + 1)],
                        "window_decades": result["window_decades"],
                        "high_end_snr": result["high_end_snr"],
                    }
                )

    print(
        json.dumps(
            {
                "gates": gates,
                "verdict": verdict,
                "interpretation": summary["interpretation"],
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
