"""Assemble results/summary.md from the Phase A / Phase B gate JSON files."""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.abspath(os.path.join(HERE, "..", "results"))


def load(name):
    with open(os.path.join(RESULTS, name)) as f:
        return json.load(f)


def main():
    a = load("gates_summary_phaseA.json")
    b = load("gates_summary_phaseB.json")

    g1 = b["gate1_classifier_consistency"]
    g2 = b["gate2_hidden_transition"]
    g3 = a["gate3_eit_ats_background_separation"]
    g4 = b["gate4_scaling_collapse"]

    def status(ok):
        return "PASS" if ok else "FAIL"

    g1_pass = all(
        v.get("match", True) for v in g1.values() if isinstance(v, dict)
    )

    lines = []
    lines.append("# Numerical results summary: new no-go theory")
    lines.append("")
    lines.append("Generated by `src/run_phase_a.py` and `src/run_phase_b.py`, "
                  "per `new_nogo_numerical_priorities.md`.")
    lines.append("")

    lines.append("## Gate 1: classifier consistency (moment / protected-coefficient / direct fit)")
    lines.append("")
    lines.append(f"Overall: **{status(g1_pass)}**")
    lines.append("")
    lines.append("| Model | Check | Result |")
    lines.append("|---|---|---|")
    lines.append(f"| Class I | max&#124;mu_k&#124; (exact certificate) | "
                  f"{g1['class_I']['max_abs_moment']:.2e} -> {g1['class_I']['certificate']} |")
    for label in ["nu1", "nu2", "nu4"]:
        d = g1[f"class_II_{label}"]
        lines.append(f"| Class II ({label}) | moment method vs. direct fit | "
                      f"{d['nu_moment_method']} vs. {d['nu_direct_fit']:.4f} -> {status(d['match'])} |")
    d3 = g1["class_III"]
    lines.append(f"| Class III | protected coefficient F0 vs. plateau at large Gamma | "
                  f"relative error {d3['relative_plateau_error']:.2e} -> {status(d3['match'])} |")
    lines.append("")

    lines.append("## Gate 2: hidden class transition (Priority 3)")
    lines.append("")
    lines.append(f"Overall: **{status(g2['passes'])}**")
    lines.append("")
    lines.append(f"- lambda_c = {g2['lambda_c']:.6f} (root of r0(lambda) = delta_chi_S,0(lambda))")
    for tag in ["at_lambda_c", "off_lambda_c"]:
        d = g2[tag]
        lines.append(f"- {tag}: nu[chi_full] = {d['nu_chi_full_direct_fit']:.4f}, "
                      f"nu[R_S] = {d['nu_R_S_direct_fit']:.4f}, "
                      f"|chi_full| plateau = {d['chi_full_plateau']:.4f}")
    lines.append("")
    lines.append("chi_full stays Class III (nu=0) on both sides of lambda_c; "
                  "R_S transitions from nu~0 (off lambda_c) to nu~1 (at lambda_c), "
                  "confirming the hidden class transition is invisible in the total "
                  "spectrum and detected only via the full-cut difference.")
    lines.append("")

    lines.append("## Gate 3: EIT / ATS / background separation (Priority 1)")
    lines.append("")
    lines.append(f"Overall: **{status(g3['passes'])}**")
    lines.append("")
    lines.append("| Point | Omega_c/gamma31 | gamma21/gamma31 | classified as | W_S | eta_S(0) |")
    lines.append("|---|---|---|---|---|---|")
    for name in ["EIT_typical", "ATS_typical", "background_typical"]:
        d = g3[name]
        lines.append(f"| {name} | {d['Omega_c_over_g31']} | {d['gamma21_over_g31']} | "
                      f"{d['classified_as']} | {d['W_S']:.3e} | {d['eta_S(0)']:.3e} |")
    lines.append("")

    lines.append("## Gate 4: scaling collapse (Priority 4)")
    lines.append("")
    lines.append(f"Overall: **{status(g4['passes'])}**")
    lines.append("")
    lines.append(f"- Gamma values used: {g4['gammas_used']}")
    lines.append(f"- Relative collapse spread: {g4['relative_collapse_spread']:.2e} "
                  f"(threshold 0.05)")
    lines.append("")

    lines.append("## Figures")
    lines.append("")
    lines.append("- `figures/fig1_theory_unit_test.png` -- Class I/II(nu=1,2,4)/III unit tests")
    lines.append("- `figures/fig2_eit_ats_crossover.png` -- Im chi_full / Im chi_cut / Im R_S maps")
    lines.append("- `figures/fig3_hidden_class_transition.png` -- nu_eff, r0, chi_full, R_S vs lambda")
    lines.append("- `figures/fig4_scaling_collapse.png` -- Gamma*R_S vs Gamma*(lambda-lambda_c)")
    lines.append("- `figures/fig5_mechanism_map.png` -- EIT/ATS/background mechanism map")
    lines.append("")

    lines.append("## Gate 5: paper-worthiness (not automated)")
    lines.append("")
    lines.append("Requires human judgement per the priorities document; the numerical "
                  "evidence above (Gates 1-4) is the input to that judgement.")
    lines.append("")

    with open(os.path.join(RESULTS, "summary.md"), "w") as f:
        f.write("\n".join(lines) + "\n")

    print("Wrote", os.path.join(RESULTS, "summary.md"))


if __name__ == "__main__":
    main()
