"""Assemble results/summary.md from the Phase A / Phase B gate JSON files."""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.abspath(os.path.join(HERE, "..", "results"))


def load(name):
    with open(os.path.join(RESULTS, name)) as f:
        return json.load(f)


def main():
    a = load("gates_summary_phaseA.json")
    b = load("gates_summary_phaseB.json")

    g1 = b["gate1_classifier_consistency"]
    g2 = b["gate2_hidden_transition"]
    g3 = a["gate3_eit_ats_background_separation"]
    g4 = b["gate4_scaling_collapse"]

    def status(ok):
        return "PASS" if ok else "FAIL"

    g1_pass = all(
        v.get("match", True) for v in g1.values() if isinstance(v, dict)
    )

    lines = []
    lines.append("# Numerical results summary: new no-go theory")
    lines.append("")
    lines.append("Generated by `src/run_phase_a.py` and `src/run_phase_b.py`, "
                  "per `new_nogo_numerical_priorities.md`.")
    lines.append("")

    lines.append("## Gate 1: classifier consistency (moment / protected-coefficient / direct fit)")
    lines.append("")
    lines.append(f"Overall: **{status(g1_pass)}**")
    lines.append("")
    lines.append("| Model | Check | Result |")
    lines.append("|---|---|---|")
    lines.append(f"| Class I | max&#124;mu_k&#124; (exact certificate) | "
                  f"{g1['class_I']['max_abs_moment']:.2e} -> {g1['class_I']['certificate']} |")
    for label in ["nu1", "nu2", "nu4"]:
        d = g1[f"class_II_{label}"]
        lines.append(f"| Class II ({label}) | moment method vs. direct fit | "
                      f"{d['nu_moment_method']} vs. {d['nu_direct_fit']:.4f} -> {status(d['match'])} |")
    d3 = g1["class_III"]
    lines.append(f"| Class III | protected coefficient F0 vs. plateau at large Gamma | "
                  f"relative error {d3['relative_plateau_error']:.2e} -> {status(d3['match'])} |")
    lines.append("")

    lines.append("## Gate 2: hidden class transition (Priority 3)")
    lines.append("")
    lines.append(f"Overall: **{status(g2['passes'])}**")
    lines.append("")
    lines.append(f"- lambda_c = {g2['lambda_c']:.6f} (root of r0(lambda) = delta_chi_S,0(lambda))")
    for tag in ["at_lambda_c", "off_lambda_c"]:
        d = g2[tag]
        lines.append(f"- {tag}: nu[chi_full] = {d['nu_chi_full_direct_fit']:.4f}, "
                      f"nu[R_S] = {d['nu_R_S_direct_fit']:.4f}, "
                      f"|chi_full| plateau = {d['chi_full_plateau']:.4f}")
    lines.append("")
    lines.append("chi_full stays Class III (nu=0) on both sides of lambda_c; "
                  "R_S transitions from nu~0 (off lambda_c) to nu~1 (at lambda_c), "
                  "confirming the hidden class transition is invisible in the total "
                  "spectrum and detected only via the full-cut difference.")
    lines.append("")

    lines.append("## Gate 3: EIT / ATS / background separation (Priority 1)")
    lines.append("")
    lines.append(f"Overall: **{status(g3['passes'])}**")
    lines.append("")
    lines.append("| Point | Omega_c/gamma31 | gamma21/gamma31 | classified as | W_S | eta_S(0) |")
    lines.append("|---|---|---|---|---|---|")
    for name in ["EIT_typical", "ATS_typical", "background_typical"]:
        d = g3[name]
        lines.append(f"| {name} | {d['Omega_c_over_g31']} | {d['gamma21_over_g31']} | "
                      f"{d['classified_as']} | {d['W_S']:.3e} | {d['eta_S(0)']:.3e} |")
    lines.append("")

    lines.append("## Gate 4: scaling collapse (Priority 4)")
    lines.append("")
    lines.append(f"Overall: **{status(g4['passes'])}**")
    lines.append("")
    lines.append(f"- Gamma values used: {g4['gammas_used']}")
    lines.append(f"- Relative collapse spread: {g4['relative_collapse_spread']:.2e} "
                  f"(threshold 0.05)")
    lines.append("")

    lines.append("## Figures")
    lines.append("")
    lines.append("- `figures/fig1_theory_unit_test.png` -- Class I/II(nu=1,2,4)/III unit tests")
    lines.append("- `figures/fig2_eit_ats_crossover.png` -- Im chi_full / Im chi_cut / Im R_S maps")
    lines.append("- `figures/fig3_hidden_class_transition.png` -- nu_eff, r0, chi_full, R_S vs lambda")
    lines.append("- `figures/fig4_scaling_collapse.png` -- Gamma*R_S vs Gamma*(lambda-lambda_c)")
    lines.append("- `figures/fig5_mechanism_map.png` -- EIT/ATS/background mechanism map")
    lines.append("")

    lines.append("## Gate 5: paper-worthiness (not automated)")
    lines.append("")
    lines.append("Requires human judgement per the priorities document; the numerical "
                  "evidence above (Gates 1-4) is the input to that judgement.")
    lines.append("")

    # ----------------------------------------------------------------
    # Phase M: metrological (QFI) extension
    # ----------------------------------------------------------------
    m_path = os.path.join(RESULTS, "gates_summary_phaseM.json")
    if os.path.exists(m_path):
        m = load("gates_summary_phaseM.json")
        m1, m2, m3, m4, m5 = (m["gateM1_vector_readout_consistency"],
                               m["gateM2_abstract_exact_vector_transition"],
                               m["gateM3_nu_to_2nu_qfi_translation"],
                               m["gateM4_physical_interior_transition_search"],
                               m["gateM5_rank_deficiency_negative_control"])

        lines.append("---")
        lines.append("")
        lines.append("# Metrological (QFI) extension: x_S, F_Q,S ~ Gamma^-2nu")
        lines.append("")
        lines.append("Tests the candidate prediction that the tangent-vector difference "
                      "x_S = d(rho_full)/dtheta - d(rho_cut)/dtheta obeys "
                      "||x_S|| ~ Gamma^-nu, and that the sector-mediated quantum Fisher "
                      "information F_Q,S = x_S^dagger G_rho x_S ~ Gamma^-2nu, translating "
                      "the three-tier response classification into a three-tier "
                      "metrological classification.")
        lines.append("")

        lines.append("## Gate M1: vector-valued readout preserves nu")
        lines.append("")
        lines.append(f"Overall: **{status(m1['passes'])}**")
        lines.append("")
        lines.append(f"- Class I (vector) floor: {m1['class_I_floor']:.2e}")
        lines.append(f"- Class II d=0: nu = {m1['class_II_d0_nu']:.4f} (expect 1)")
        lines.append(f"- Class II d=1: nu = {m1['class_II_d1_nu']:.4f} (expect 2)")
        lines.append(f"- Class II d=3: nu = {m1['class_II_d3_nu']:.4f} (expect 4)")
        lines.append("")

        lines.append("## Gate M2: exact vector hidden class transition (abstract, rank-1 cut)")
        lines.append("")
        lines.append(f"Overall: **{status(m2['passes'])}**")
        lines.append("")
        lines.append(f"- lambda_c0 = {m2['lambda_c0']:.6f} (closed-form leading-order root, no search needed)")
        lines.append(f"- at lambda_c: nu = {m2['at_lambda_c']['nu']:.4f}")
        lines.append(f"- off lambda_c: nu = {m2['off_lambda_c']['nu']:.4f}")
        lines.append(f"- scaling collapse relative spread: {m2['collapse_relative_spread']:.2e}")
        lines.append("")
        lines.append("The rank-1 (non-Hermitian, Sherman-Morrison) sector cut gives the "
                      "difference x_S the fixed-direction-times-scalar structure needed for "
                      "the *whole vector* to vanish together at a single real control value, "
                      "confirming the vector generalization of the hidden class transition "
                      "exactly, within the abstract scope of Theorem III (no Hermiticity "
                      "assumed there).")
        lines.append("")

        lines.append("## Gate M3: nu -> 2nu QFI translation (physical 3-level Lindblad model)")
        lines.append("")
        lines.append(f"Overall: **{status(m3['passes'])}**")
        lines.append("")
        lines.append(f"- nu[x_S] (direct fit) = {m3['nu_x']:.4f}")
        lines.append(f"- nu[F_Q,S] (direct fit, should be ~2*nu[x_S]) = {m3['nu_F']:.4f}")
        lines.append(f"- ratio nu_F / (2 nu_x) = {m3['ratio_nuF_over_2nuX']:.4f}")
        lines.append(f"- SLD minimum-eigenvalue range over the Gamma sweep: {m3['min_eigenvalue_range']}")
        lines.append("")
        lines.append("This is the core numerical confirmation of the user's prediction: "
                      "in a genuine 3-level Lindblad master equation with a Gamma-scaled "
                      "singular dissipator, the sector-mediated QFI decays exactly twice "
                      "as fast (in the Gamma^-nu sense) as the tangent-vector norm itself.")
        lines.append("")

        lines.append("## Gate M4: physical (Hermitian-coupling) interior transition search")
        lines.append("")
        lines.append(f"Interior transition found: **{m4['interior_transition_found']}**")
        lines.append("")
        lines.append(f"- generic-point norm: {m4['generic_point_norm']:.3e}")
        lines.append(f"- best found (2D search) norm: {m4['best_found_norm']:.3e}")
        lines.append(f"- suppression ratio vs. generic: {m4['suppression_ratio_vs_generic']:.2f}")
        lines.append("")
        lines.append(m4["interpretation"])
        lines.append("")

        lines.append("## Gate M5: rank-deficiency negative control")
        lines.append("")
        lines.append(f"Overall: **{status(m5['passes'])}**")
        lines.append("")
        for tag in ["normal_epsilon", "tiny_epsilon"]:
            d = m5[tag]
            lines.append(f"- {tag} (epsilon={d['epsilon']}): nu_x={d['nu_x']:.4f}, "
                          f"nu_F={d['nu_F']:.4f}, ratio={d['ratio_nuF_over_2nuX']:.4f}, "
                          f"min eigenvalue at Gamma_max = {d['min_eigenvalue_at_Gmax']:.2e}")
        lines.append("")
        lines.append("As epsilon -> 0 the steady state approaches a near-pure (rank-deficient) "
                      "state, the SLD metric approaches singularity, and the clean "
                      "nu_F = 2*nu_x relation degrades -- confirming that the 'full rank / "
                      "non-singular SLD metric' assumption in the prediction is load-bearing, "
                      "not decorative.")
        lines.append("")

        lines.append("## Phase M figures")
        lines.append("")
        lines.append("- `figures/figM1_vector_unit_test.png`")
        lines.append("- `figures/figM2_abstract_vector_transition.png`")
        lines.append("- `figures/figM3_qfi_translation.png`")
        lines.append("- `figures/figM4_physical_lambda_phi_scan.png`")
        lines.append("- `figures/figM5_rank_deficiency_control.png`")
        lines.append("")

    with open(os.path.join(RESULTS, "summary.md"), "w") as f:
        f.write("\n".join(lines) + "\n")

    print("Wrote", os.path.join(RESULTS, "summary.md"))


if __name__ == "__main__":
    main()
